server:
  port: 8081

spring:
  application:
    name: NeoBank
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_app
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: 'init'
    baseline-version: 1

application:
  security:
    jwt:
      secret-key: 7922255b70a1e19c2542cb91542333978f680542ee2d8cb7cd96ee08fe5f54cd