server:
  port: 8081

spring:
  application:
    name: NeoBank
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_app
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: 'init'
    baseline-version: 1
