package com.zouhir.neobank.account;

import com.zouhir.neobank.common.exceptions.InsufficientBalanceException;
import com.zouhir.neobank.user.User;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

@Entity
@Builder
@Getter
//@Setter
@AllArgsConstructor
@NoArgsConstructor( access = AccessLevel.PROTECTED) // prevent using the default constructor from somewhere , new Account() without any infos
@Table(name = "accounts")
public class Account {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY) //avoid EAGER fetching , to avoid charging unnecessary data when non needed
    @JoinColumn(name = "user_id", nullable = false, updatable = false)
    private User user;

    @Column(name = "account_no", nullable = false, updatable = false, unique = true)
    private String accountNo;

    @Builder.Default // forcing the builder to use the default value for this field
    @Column(precision = 19, scale = 4 , nullable = false)
    private BigDecimal balance = BigDecimal.ZERO;

    @Builder.Default
    @Column(nullable = false)
    private String currency = "EUR";

    @Version
    private Integer version;

    @Builder.Default
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private Status status = Status.ACTIVE;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @PrePersist
    public void onCreate(){
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    @PreUpdate
    public void onUpdate(){
        this.updatedAt = Instant.now();
    }

    @Override
    public boolean equals(Object other){
        if(this == other) return true;
        if(!(other instanceof Account account)) return false;
        return Objects.equals(this.getAccountNo(), account.getAccountNo());
    }

    @Override
    public int hashCode(){
        return Objects.hash(getAccountNo());
    } // we use accountNo and not id, because id at first is null (proxy) before the account saved and id autogenerated, otherwise if we use id , we will loose our object (hashset, hashmap...)

    public void debit(BigDecimal amount){
        if(amount == null || amount.compareTo(BigDecimal.ZERO) < 0 ){
            throw new IllegalArgumentException("Error : The amount should be greater than zero !");
        }
        if(this.getBalance().compareTo(amount) < 0){
            throw new InsufficientBalanceException("Error : Insufficient balance to debit : "+amount);
        }
        this.balance = this.balance.subtract(amount);
    }

    public void credit(BigDecimal amount){
        if(amount == null || amount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException(("Error : The amount should be greater than zero !"));
        }
        this.balance = this.balance.add(amount);
    }
}


